# 指定されていない項目はデフォルト値が使用されます。環境変数も同様です
# 環境変数からも読み込むことのできる項目はすべてアンダーバー `_` から始まります
# その項目が環境変数から読み込まれるかは envのbooleanを確認してください
# ex:  _name: ""

# databaseとの接続情報を指定します
database:
  # シーズンによって削除されない永続的なデータを管理する
  main:
    # sqlite, mariadb, mysql
    type: sqlite                      # sqlite
    # テーブルに付与する接頭語
    table_prefix: "sc_"               # ""

    # jdbc urlを指定します
    # typeがsqliteの場合は空白にするとデフォルトのファイルが使用されます (data.db)
    # プレースホルダーで環境変数を読み込むこともできます ${VAR_NAME}
    url: "jdbc:sqlite:plugins/ShardCore/main.db"          # ""
    username: "root"                # "root"
    password: ""                    # ""

  # シーズンによって削除されるデータを管理する
  season:
    type: sqlite
    table_prefix: ""
    url: "jdbc:sqlite:plugins/ShardCore/season.db"
    username: "root"
    password: ""

# すべてのデータを定期的に保存する間隔 (単位: 秒)
auto_save_interval: 300           # 300
