name: ShardCore
version: '${version}'
main: net.logiench.shardCore.ShardCore
description: ''
api-version: '1.21.8'
bootstrapper: net.logiench.shardCore.ShardCoreBootstrap
#loader:

authors:
  - masa355
  - marry586

dependencies:
  server:
    LogienchLib:
      load: BEFORE
      required: true
      join-classpath: true
    ShardLib:
      load: BEFORE
      required: true
      join-classpath: true
