name: LogienchLib
version: '${version}'
description: "Project-Logiench の便利機能ライブラリです"
author: "masa355"
main: net.logiench.logienchlibv2.LogienchLib
api-version: '1.20'
depend:
  - ProtocolLib
  - floodgate
softdepend:
  - NBTAPI

commands:
  logienchlib:
    description: LogienchLib commands
    usage: /<command> <type> ...
    permission: op
    aliases: [ ll ]
