name: ShardLib
version: '${version}'
main: net.logiench.shardLib.ShardLib
api-version: '1.20'
authors: [ masa355 ]
description: "RPG系の根幹システムをいい感じに提供してくれるライブラリです"
commands:
  shardlib:
    description: ShardLib commands
    usage: /<command> <type> ...
    permission: op
    aliases: [ sl ]

depend:
  - LogienchLib